name: iota_one_test
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  equatable: ^2.0.3
  # state management (BloC)
  flutter_bloc: ^7.2.0

  # http
  http: ^0.13.3

  # dependency injection
  get_it: ^7.2.0
  injectable: ^1.5.0

  # database
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  # json serializing
  json_serializable: ^6.1.1

  #  connectivity
  connectivity: ^3.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.1
  build_runner: ^2.1.5
  json_serializable: ^6.1.1
  retrofit_generator: 3.0.0+2
  floor_generator: 1.2.0
  injectable_generator: ^1.5.2
  http: ^0.13.4
  hive_generator: ^1.1.1
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

